app/views/layouts/application.html.erb

Add favicon

---

app/controllers/agences_controller.rb
app/models/agence.rb
db/migrate/20180827143427_create_agences.rb
db/schema.rb
test/controllers/agences_controller_test.rb
test/models/agence_test.rb

create agence model

---

app/controllers/owners_controller.rb
app/models/owner.rb
db/migrate/20180827150316_create_owners.rb
test/controllers/owners_controller_test.rb
test/models/owner_test.rb

create model and controller for owners

---

app/models/agence.rb
app/models/agent.rb
db/migrate/20180827145522_create_agents.rb
db/seeds.rb
test/models/agent_test.rb

agent and first seed

---

Gemfile
Gemfile.lock
app/controllers/houses_controller.rb
app/models/house.rb
config/initializers/money.rb
db/migrate/20180827152738_create_houses.rb
db/schema.rb
test/controllers/houses_controller_test.rb
test/models/house_test.rb

Create home model

---

app/models/house.rb
db/migrate/20180827162427_add_price_to_houses.rb
db/schema.rb

price added

---

app/models/agence.rb
db/migrate/20180827152738_create_houses.rb
db/schema.rb

no errors now in migrations

---

.gitignore
Gemfile
Gemfile.lock
app/assets/stylesheets/components/_card.scss
app/controllers/houses_controller.rb
app/models/house.rb
app/uploaders/photo_uploader.rb
app/views/houses/index.html.erb
config/routes.rb
db/migrate/20180827152738_create_houses.rb
db/migrate/20180827165901_add_photo_to_houses.rb
db/schema.rb

cloudinary config hors heroku

---

app/views/houses/show.html.erb

added all data from house in show

---

app/controllers/document_controller.rb
app/controllers/document_type_controller.rb
app/models/document.rb
app/models/document_type.rb
app/models/owner.rb
app/models/user.rb
db/migrate/20180828100520_create_document_types.rb
db/migrate/20180828100733_create_documents.rb
db/schema.rb
db/seeds.rb
test/controllers/document_controller_test.rb
test/controllers/document_type_controller_test.rb
test/models/document_test.rb
test/models/document_type_test.rb

Latest tables

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/controllers/houses_controller.rb
app/policies/application_policy.rb
app/policies/house_policy.rb
test/policies/house_policy_test.rb

pundit config done

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/houses/_index.scss
app/assets/stylesheets/houses/_show.scss
app/views/houses/show.html.erb

first draft of show

---

app/views/houses/_form_houses.html.erb
app/views/houses/new.html.erb

formulaire début

---

app/assets/stylesheets/houses/_show.scss
app/models/house.rb
app/views/houses/show.html.erb

premiere version du show de la house

show house first

---

app/controllers/application_controller.rb
app/views/devise/registrations/new.html.erb

fixing sign up

---

app/controllers/houses_controller.rb
app/controllers/owners_controller.rb
app/views/houses/_form_houses1.html.erb
config/routes.rb

@CharlesGTY 
formulaire qui marche et controller

owner controller and form

---

app/controllers/documents_controller.rb
app/views/documents/show.pdf.erb
app/views/houses/show.html.erb
config/initializers/wicked_pdf.rb

first pdf generation done

---

app/assets/stylesheets/components/_boxes.scss
app/assets/stylesheets/components/_btn.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_list.scss
app/assets/stylesheets/config/_colors.scss
app/javascript/packs/application.js
app/javascript/packs/components/index.js
app/javascript/packs/components/navbar-fixed.js
app/views/shared/_listing-houses.html.erb
app/views/shared/_numbers-houses.html.erb

Index show

---

app/assets/stylesheets/pdf.css
app/controllers/documents_controller.rb
app/views/documents/show.pdf.erb
app/views/layouts/pdf.html.erb
config/initializers/wicked_pdf.rb

css en cours

---

app/views/shared/_listing-houses.html.erb

fixing button link

---

app/views/layouts/pdf.html.erb

delete googleapi css from css file of pdf

---

app/assets/stylesheets/pdf.css
app/controllers/documents_controller.rb
app/views/documents/show.pdf.erb
app/views/houses/index.html.erb
app/views/layouts/pdf.html.erb
config/initializers/assets.rb
db/seeds.rb

Formulaire creation

---

app/assets/stylesheets/layouts/_index.scss
app/views/layouts/application.html.erb

pdf done and footer fixed

---

app/controllers/documents_controller.rb
app/models/document.rb
app/views/shared/_document-juridiques.html.erb

pdf fixing

---

app/views/houses/_form_houses.html.erb

showing progress

---

app/assets/stylesheets/houses/_new.scss

reducing width of progress bar

---

app/assets/stylesheets/pages/_home.scss
app/views/pages/home.html.erb

Bugs fixing

---

app/views/pages/home.html.erb

phrase dans description

---

app/controllers/application_controller.rb

redirect login

---

app/assets/stylesheets/houses/_new.scss

black form

---

app/assets/stylesheets/pages/_home.scss
app/views/pages/home.html.erb

bouton page accueil

---

app/assets/stylesheets/components/_list.scss
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/shared/_listing-houses.html.erb
app/views/shared/_navbar.html.erb
db/seeds.rb

Form fixing

---

app/assets/stylesheets/pdf.css
app/views/shared/_navbar.html.erb

pdf smaller et navbar redirect

pdf smaller et navbar redirect

---

app/assets/stylesheets/components/_footer.scss
app/views/shared/_footer.html.erb

footer good

---

app/assets/stylesheets/components/_navbar.scss
app/views/pages/home.html.erb
app/views/shared/_navbar.html.erb

Changementnavbar

---

app/assets/stylesheets/houses/_new.scss
app/controllers/houses_controller.rb
app/views/houses/_form_houses.html.erb

New house form

---

app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/pages/_home.scss

reglage des container

---

app/controllers/houses_controller.rb
app/models/house.rb
app/views/houses/_form_houses.html.erb
app/views/houses/new.html.erb
app/views/houses/show.html.erb
app/views/shared/_house-information.html.erb

Various fixes

---

app/assets/stylesheets/components/_btn.scss
app/assets/stylesheets/components/_list.scss

modif bouton et ajustements page listing

modif bouton et ajustements page listing

---

db/seeds.rb

meilleur seed

---

app/views/layouts/application.html.erb

fooster is gone

---

app/views/houses/_form_houses.html.erb

form Enter

---

app/views/layouts/application.html.erb

metadonnees facebook

---

public/404.html
public/500.html

pages erreur

---

app/assets/stylesheets/components/_list.scss
app/assets/stylesheets/houses/_show.scss

marge listing alignee et meilleur taille des mandats generes

---

db/seeds.rb

enlever document type dans seeds

---

app/views/shared/_banner-show.html.erb
app/views/shared/_house-information.html.erb

better version of prices

---

app/controllers/houses_controller.rb

filtres sur biens eclusifs

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_loading.scss
app/assets/stylesheets/houses/_show.scss
app/javascript/components/alter.js
app/javascript/components/loading.js
app/javascript/packs/application.js
app/views/shared/_document-juridiques.html.erb

js polooooooolowwwwww

---

app/models/house.rb
app/views/houses/_form_houses.html.erb
db/migrate/20180830120755_add_columns_to_house.rb
db/schema.rb

various bug fixes

---

public/404.html
public/500.html

erreur 404 et 500

---

app/views/houses/_form_houses.html.erb

first version

---

app/assets/stylesheets/components/_boxes.scss
app/javascript/packs/application.js
app/views/shared/_numbers-houses.html.erb

button filter

---

app/assets/stylesheets/components/_list.scss
app/views/shared/_listing-houses.html.erb
db/seeds.rb

add agent ref icon and surface on each index line

---

app/assets/stylesheets/houses/_show.scss
app/views/shared/_banner-show.html.erb
app/views/shared/_listing-houses.html.erb

les agents des biens dans l'index et dans la show sont les memes

---

app/assets/stylesheets/components/show_doc.scss
app/views/houses/show_doc.html.erb

Historyfaking

---

app/assets/stylesheets/components/_avatar.scss
app/assets/stylesheets/components/_boxes.scss
app/assets/stylesheets/components/_list.scss
app/assets/stylesheets/houses/_show.scss
app/views/shared/_banner-show.html.erb
app/views/shared/_document-juridiques.html.erb
app/views/shared/_listing-houses.html.erb

Boutonesign
